-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity write_u32 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_uart_AWVALID : OUT STD_LOGIC;
    m_axi_uart_AWREADY : IN STD_LOGIC;
    m_axi_uart_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_uart_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_uart_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_uart_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_uart_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_uart_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_uart_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_uart_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_uart_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_uart_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_uart_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_uart_WVALID : OUT STD_LOGIC;
    m_axi_uart_WREADY : IN STD_LOGIC;
    m_axi_uart_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_uart_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_uart_WLAST : OUT STD_LOGIC;
    m_axi_uart_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_uart_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_uart_ARVALID : OUT STD_LOGIC;
    m_axi_uart_ARREADY : IN STD_LOGIC;
    m_axi_uart_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_uart_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_uart_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_uart_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_uart_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_uart_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_uart_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_uart_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_uart_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_uart_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_uart_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_uart_RVALID : IN STD_LOGIC;
    m_axi_uart_RREADY : OUT STD_LOGIC;
    m_axi_uart_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_uart_RLAST : IN STD_LOGIC;
    m_axi_uart_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_uart_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_uart_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_uart_BVALID : IN STD_LOGIC;
    m_axi_uart_BREADY : OUT STD_LOGIC;
    m_axi_uart_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_uart_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_uart_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    uart_offset : IN STD_LOGIC_VECTOR (29 downto 0);
    value_r : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of write_u32 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv7_37 : STD_LOGIC_VECTOR (6 downto 0) := "0110111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal k_fu_87_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal k_reg_165 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln139_1_fu_114_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln139_1_reg_170 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln138_fu_81_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln140_fu_143_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln140_reg_177 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_write_byte_fu_73_ap_start : STD_LOGIC;
    signal grp_write_byte_fu_73_ap_done : STD_LOGIC;
    signal grp_write_byte_fu_73_ap_idle : STD_LOGIC;
    signal grp_write_byte_fu_73_ap_ready : STD_LOGIC;
    signal grp_write_byte_fu_73_m_axi_uart_AWVALID : STD_LOGIC;
    signal grp_write_byte_fu_73_m_axi_uart_AWADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_WVALID : STD_LOGIC;
    signal grp_write_byte_fu_73_m_axi_uart_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_WLAST : STD_LOGIC;
    signal grp_write_byte_fu_73_m_axi_uart_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_ARVALID : STD_LOGIC;
    signal grp_write_byte_fu_73_m_axi_uart_ARADDR : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_write_byte_fu_73_m_axi_uart_RREADY : STD_LOGIC;
    signal grp_write_byte_fu_73_m_axi_uart_BREADY : STD_LOGIC;
    signal k_0_reg_62 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_write_byte_fu_73_ap_start_reg : STD_LOGIC := '0';
    signal trunc_ln139_fu_93_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal shl_ln_fu_97_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln139_fu_105_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln139_fu_109_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_ln_fu_126_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln143_fu_123_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal icmp_ln140_fu_118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln140_fu_133_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln140_fu_137_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);

    component write_byte IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_uart_AWVALID : OUT STD_LOGIC;
        m_axi_uart_AWREADY : IN STD_LOGIC;
        m_axi_uart_AWADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_uart_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_uart_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_uart_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_uart_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_uart_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_uart_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_uart_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_uart_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_uart_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_uart_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_uart_WVALID : OUT STD_LOGIC;
        m_axi_uart_WREADY : IN STD_LOGIC;
        m_axi_uart_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_uart_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_uart_WLAST : OUT STD_LOGIC;
        m_axi_uart_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_uart_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_uart_ARVALID : OUT STD_LOGIC;
        m_axi_uart_ARREADY : IN STD_LOGIC;
        m_axi_uart_ARADDR : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_uart_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_uart_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_uart_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_uart_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_uart_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_uart_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_uart_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_uart_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_uart_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_uart_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_uart_RVALID : IN STD_LOGIC;
        m_axi_uart_RREADY : OUT STD_LOGIC;
        m_axi_uart_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_uart_RLAST : IN STD_LOGIC;
        m_axi_uart_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_uart_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_uart_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_uart_BVALID : IN STD_LOGIC;
        m_axi_uart_BREADY : OUT STD_LOGIC;
        m_axi_uart_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_uart_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_uart_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        uart_offset : IN STD_LOGIC_VECTOR (29 downto 0);
        data : IN STD_LOGIC_VECTOR (6 downto 0) );
    end component;



begin
    grp_write_byte_fu_73 : component write_byte
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_write_byte_fu_73_ap_start,
        ap_done => grp_write_byte_fu_73_ap_done,
        ap_idle => grp_write_byte_fu_73_ap_idle,
        ap_ready => grp_write_byte_fu_73_ap_ready,
        m_axi_uart_AWVALID => grp_write_byte_fu_73_m_axi_uart_AWVALID,
        m_axi_uart_AWREADY => m_axi_uart_AWREADY,
        m_axi_uart_AWADDR => grp_write_byte_fu_73_m_axi_uart_AWADDR,
        m_axi_uart_AWID => grp_write_byte_fu_73_m_axi_uart_AWID,
        m_axi_uart_AWLEN => grp_write_byte_fu_73_m_axi_uart_AWLEN,
        m_axi_uart_AWSIZE => grp_write_byte_fu_73_m_axi_uart_AWSIZE,
        m_axi_uart_AWBURST => grp_write_byte_fu_73_m_axi_uart_AWBURST,
        m_axi_uart_AWLOCK => grp_write_byte_fu_73_m_axi_uart_AWLOCK,
        m_axi_uart_AWCACHE => grp_write_byte_fu_73_m_axi_uart_AWCACHE,
        m_axi_uart_AWPROT => grp_write_byte_fu_73_m_axi_uart_AWPROT,
        m_axi_uart_AWQOS => grp_write_byte_fu_73_m_axi_uart_AWQOS,
        m_axi_uart_AWREGION => grp_write_byte_fu_73_m_axi_uart_AWREGION,
        m_axi_uart_AWUSER => grp_write_byte_fu_73_m_axi_uart_AWUSER,
        m_axi_uart_WVALID => grp_write_byte_fu_73_m_axi_uart_WVALID,
        m_axi_uart_WREADY => m_axi_uart_WREADY,
        m_axi_uart_WDATA => grp_write_byte_fu_73_m_axi_uart_WDATA,
        m_axi_uart_WSTRB => grp_write_byte_fu_73_m_axi_uart_WSTRB,
        m_axi_uart_WLAST => grp_write_byte_fu_73_m_axi_uart_WLAST,
        m_axi_uart_WID => grp_write_byte_fu_73_m_axi_uart_WID,
        m_axi_uart_WUSER => grp_write_byte_fu_73_m_axi_uart_WUSER,
        m_axi_uart_ARVALID => grp_write_byte_fu_73_m_axi_uart_ARVALID,
        m_axi_uart_ARREADY => m_axi_uart_ARREADY,
        m_axi_uart_ARADDR => grp_write_byte_fu_73_m_axi_uart_ARADDR,
        m_axi_uart_ARID => grp_write_byte_fu_73_m_axi_uart_ARID,
        m_axi_uart_ARLEN => grp_write_byte_fu_73_m_axi_uart_ARLEN,
        m_axi_uart_ARSIZE => grp_write_byte_fu_73_m_axi_uart_ARSIZE,
        m_axi_uart_ARBURST => grp_write_byte_fu_73_m_axi_uart_ARBURST,
        m_axi_uart_ARLOCK => grp_write_byte_fu_73_m_axi_uart_ARLOCK,
        m_axi_uart_ARCACHE => grp_write_byte_fu_73_m_axi_uart_ARCACHE,
        m_axi_uart_ARPROT => grp_write_byte_fu_73_m_axi_uart_ARPROT,
        m_axi_uart_ARQOS => grp_write_byte_fu_73_m_axi_uart_ARQOS,
        m_axi_uart_ARREGION => grp_write_byte_fu_73_m_axi_uart_ARREGION,
        m_axi_uart_ARUSER => grp_write_byte_fu_73_m_axi_uart_ARUSER,
        m_axi_uart_RVALID => m_axi_uart_RVALID,
        m_axi_uart_RREADY => grp_write_byte_fu_73_m_axi_uart_RREADY,
        m_axi_uart_RDATA => m_axi_uart_RDATA,
        m_axi_uart_RLAST => m_axi_uart_RLAST,
        m_axi_uart_RID => m_axi_uart_RID,
        m_axi_uart_RUSER => m_axi_uart_RUSER,
        m_axi_uart_RRESP => m_axi_uart_RRESP,
        m_axi_uart_BVALID => m_axi_uart_BVALID,
        m_axi_uart_BREADY => grp_write_byte_fu_73_m_axi_uart_BREADY,
        m_axi_uart_BRESP => m_axi_uart_BRESP,
        m_axi_uart_BID => m_axi_uart_BID,
        m_axi_uart_BUSER => m_axi_uart_BUSER,
        uart_offset => uart_offset,
        data => select_ln140_reg_177);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_write_byte_fu_73_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_write_byte_fu_73_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_write_byte_fu_73_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_write_byte_fu_73_ap_ready = ap_const_logic_1)) then 
                    grp_write_byte_fu_73_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    k_0_reg_62_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_write_byte_fu_73_ap_done = ap_const_logic_1))) then 
                k_0_reg_62 <= k_reg_165;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                k_0_reg_62 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                k_reg_165 <= k_fu_87_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                select_ln140_reg_177 <= select_ln140_fu_143_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln138_fu_81_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                trunc_ln139_1_reg_170 <= trunc_ln139_1_fu_114_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln138_fu_81_p2, grp_write_byte_fu_73_ap_done, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln138_fu_81_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_write_byte_fu_73_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln140_fu_137_p2 <= std_logic_vector(unsigned(ap_const_lv7_37) + unsigned(zext_ln143_fu_123_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln138_fu_81_p2)
    begin
        if ((((icmp_ln138_fu_81_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln138_fu_81_p2)
    begin
        if (((icmp_ln138_fu_81_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_write_byte_fu_73_ap_start <= grp_write_byte_fu_73_ap_start_reg;
    icmp_ln138_fu_81_p2 <= "1" when (k_0_reg_62 = ap_const_lv4_8) else "0";
    icmp_ln140_fu_118_p2 <= "1" when (unsigned(trunc_ln139_1_reg_170) < unsigned(ap_const_lv4_A)) else "0";
    k_fu_87_p2 <= std_logic_vector(unsigned(k_0_reg_62) + unsigned(ap_const_lv4_1));
    lshr_ln139_fu_109_p2 <= std_logic_vector(shift_right(unsigned(value_r),to_integer(unsigned('0' & zext_ln139_fu_105_p1(31-1 downto 0)))));
    m_axi_uart_ARADDR <= grp_write_byte_fu_73_m_axi_uart_ARADDR;
    m_axi_uart_ARBURST <= grp_write_byte_fu_73_m_axi_uart_ARBURST;
    m_axi_uart_ARCACHE <= grp_write_byte_fu_73_m_axi_uart_ARCACHE;
    m_axi_uart_ARID <= grp_write_byte_fu_73_m_axi_uart_ARID;
    m_axi_uart_ARLEN <= grp_write_byte_fu_73_m_axi_uart_ARLEN;
    m_axi_uart_ARLOCK <= grp_write_byte_fu_73_m_axi_uart_ARLOCK;
    m_axi_uart_ARPROT <= grp_write_byte_fu_73_m_axi_uart_ARPROT;
    m_axi_uart_ARQOS <= grp_write_byte_fu_73_m_axi_uart_ARQOS;
    m_axi_uart_ARREGION <= grp_write_byte_fu_73_m_axi_uart_ARREGION;
    m_axi_uart_ARSIZE <= grp_write_byte_fu_73_m_axi_uart_ARSIZE;
    m_axi_uart_ARUSER <= grp_write_byte_fu_73_m_axi_uart_ARUSER;

    m_axi_uart_ARVALID_assign_proc : process(ap_CS_fsm_state3, grp_write_byte_fu_73_m_axi_uart_ARVALID, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_uart_ARVALID <= grp_write_byte_fu_73_m_axi_uart_ARVALID;
        else 
            m_axi_uart_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_uart_AWADDR <= grp_write_byte_fu_73_m_axi_uart_AWADDR;
    m_axi_uart_AWBURST <= grp_write_byte_fu_73_m_axi_uart_AWBURST;
    m_axi_uart_AWCACHE <= grp_write_byte_fu_73_m_axi_uart_AWCACHE;
    m_axi_uart_AWID <= grp_write_byte_fu_73_m_axi_uart_AWID;
    m_axi_uart_AWLEN <= grp_write_byte_fu_73_m_axi_uart_AWLEN;
    m_axi_uart_AWLOCK <= grp_write_byte_fu_73_m_axi_uart_AWLOCK;
    m_axi_uart_AWPROT <= grp_write_byte_fu_73_m_axi_uart_AWPROT;
    m_axi_uart_AWQOS <= grp_write_byte_fu_73_m_axi_uart_AWQOS;
    m_axi_uart_AWREGION <= grp_write_byte_fu_73_m_axi_uart_AWREGION;
    m_axi_uart_AWSIZE <= grp_write_byte_fu_73_m_axi_uart_AWSIZE;
    m_axi_uart_AWUSER <= grp_write_byte_fu_73_m_axi_uart_AWUSER;

    m_axi_uart_AWVALID_assign_proc : process(ap_CS_fsm_state3, grp_write_byte_fu_73_m_axi_uart_AWVALID, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_uart_AWVALID <= grp_write_byte_fu_73_m_axi_uart_AWVALID;
        else 
            m_axi_uart_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_uart_BREADY_assign_proc : process(ap_CS_fsm_state3, grp_write_byte_fu_73_m_axi_uart_BREADY, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_uart_BREADY <= grp_write_byte_fu_73_m_axi_uart_BREADY;
        else 
            m_axi_uart_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_uart_RREADY_assign_proc : process(ap_CS_fsm_state3, grp_write_byte_fu_73_m_axi_uart_RREADY, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_uart_RREADY <= grp_write_byte_fu_73_m_axi_uart_RREADY;
        else 
            m_axi_uart_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_uart_WDATA <= grp_write_byte_fu_73_m_axi_uart_WDATA;
    m_axi_uart_WID <= grp_write_byte_fu_73_m_axi_uart_WID;
    m_axi_uart_WLAST <= grp_write_byte_fu_73_m_axi_uart_WLAST;
    m_axi_uart_WSTRB <= grp_write_byte_fu_73_m_axi_uart_WSTRB;
    m_axi_uart_WUSER <= grp_write_byte_fu_73_m_axi_uart_WUSER;

    m_axi_uart_WVALID_assign_proc : process(ap_CS_fsm_state3, grp_write_byte_fu_73_m_axi_uart_WVALID, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            m_axi_uart_WVALID <= grp_write_byte_fu_73_m_axi_uart_WVALID;
        else 
            m_axi_uart_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    or_ln_fu_126_p3 <= (ap_const_lv2_3 & trunc_ln139_1_reg_170);
    select_ln140_fu_143_p3 <= 
        zext_ln140_fu_133_p1 when (icmp_ln140_fu_118_p2(0) = '1') else 
        add_ln140_fu_137_p2;
    shl_ln_fu_97_p3 <= (trunc_ln139_fu_93_p1 & ap_const_lv2_0);
    trunc_ln139_1_fu_114_p1 <= lshr_ln139_fu_109_p2(4 - 1 downto 0);
    trunc_ln139_fu_93_p1 <= k_0_reg_62(3 - 1 downto 0);
    zext_ln139_fu_105_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_97_p3),32));
    zext_ln140_fu_133_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_126_p3),7));
    zext_ln143_fu_123_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(trunc_ln139_1_reg_170),7));
end behav;
